website/dnswebsite/DNSmisconfiguration/urls.py
from django.urls import path

from . import views


app_name = 'DNSmisconfiguration'

urlpatterns = [
    path('', views.index, name='index'),
    path('readme', views.readme, name='readme'),
    path('address', views.address, name='address'),
    path('csv_url', views.csv_url, name='csv_url'),
    path('known_ns', views.known_ns, name='known_ns'),
    path('results/<int:dict_id>', views.results, name='results'),
    path('top500', views.top500, name='top500'),
    path('download_dict/<int:dict_id>/<int:option>', views.download_dict, name='download_dict'),
    path('download_results_servers', views.download_results_servers, name='download_results_servers'),
    path('download_results_records', views.download_results_records, name='download_results_records'),
    path('download_misconfigurations', views.download_misconfigurations, name='download_misconfigurations'),
    path('download_misconfigurations_count', views.download_misconfigurations_count, name='download_misconfigurations_count'),
    path('download_top500_results_servers', views.download_top500_results_servers, name='download_top500_results_servers'),
    path('download_top500_results_records', views.download_top500_results_records, name='download_top500_results_records'),
    path('download_top500_misconfigurations', views.download_top500_misconfigurations, name='download_top500_misconfigurations'),
    path('download_top500_misconfigurations_count', views.download_top500_misconfigurations_count, name='download_top500_misconfigurations_count')
]

website/dnswebsite/dnswebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('DNSmisconfiguration.urls')),
    path('admin/', admin.site.urls),
]

website/dnswebsite/DNSmisconfiguration/models.py
from django.db import models


class Server(models.Model):
    host_name = models.CharField(primary_key=True, max_length=256, default="")
    description = models.CharField(max_length=512, default="")
    original_domain = models.CharField(max_length=256, default="")

    def __str__(self):
        return str(self.host_name)


class AddressIPv4(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField(protocol='IPv4')

    def __str__(self):
        return str(self.ip_address) + " (" + str(self.server.host_name) + ")"


class AddressIPv6(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField(protocol='IPv6')

    def __str__(self):
        return str(self.ip_address) + " (" + str(self.server.host_name) + ")"


class KnownNameServer(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    domain = models.CharField(max_length=512, default="")
    known_server = models.CharField(max_length=256, default="")

    def __str__(self):
        return "(" + str(self.server.host_name) + ", " + str(self.domain) + ") --> " + str(self.known_server)


class RootDNSServers(models.Model):
    host_name = models.CharField(primary_key=True, max_length=256, default="")
    ipv4_address = models.GenericIPAddressField(protocol='IPv4')
    ipv6_address = models.GenericIPAddressField(protocol='IPv6')
    description = models.CharField(max_length=512, default="")


class StoredDict(models.Model):
    pickle_dict = models.BinaryField()

website/dnswebsite/DNSmisconfiguration/forms.py
from django import forms


class SingleUrlForm(forms.Form):
    url = forms.CharField(required=True, max_length=512, label="URL")


class UploadFileForm(forms.Form):
    file = forms.FileField()

website/dnswebsite/DNSmisconfiguration/views.py
import os
import pickle
import csv
from ast import literal_eval
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.http import StreamingHttpResponse, Http404, HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from . import dns_utils, CheckCSV
from .forms import SingleUrlForm, UploadFileForm
from .models import StoredDict, RootDNSServers


class Member:
    def __init__(self, name, role="Project Member", brief=None, email="Not Allowed", image="", image_alt=None):
        self.name = name
        self.role = role
        self.brief = brief if brief is not None else "Acts as a " + role + " in this project"
        self.email = email
        self.image = "DNSmisconfiguration/" + image
        self.image_alt = image_alt if image_alt is not None else "Image of " + name


def handle_dns(dns_worker, misconfiguration_result):
    information = StoredDict.objects.create(pickle_dict=pickle.dumps(dns_worker.name_to_server_info_dict))
    dns = StoredDict.objects.create(pickle_dict=pickle.dumps(dns_worker.DNS_dict))
    misconfiguration_data = StoredDict.objects.create(pickle_dict=pickle.dumps(misconfiguration_result.misconfiguration_dict))
    misconfiguration_count = StoredDict.objects.create(pickle_dict=pickle.dumps(misconfiguration_result.misconfiguration_count_dict))

    sorted_misconfiguration_count = sorted(misconfiguration_result.misconfiguration_count_dict.items(), key=lambda kv: (kv[1], kv[0]), reverse=True)

    top10_misconfiguration_count = sorted_misconfiguration_count[:10]

    domains = list(map(lambda a: a[0], top10_misconfiguration_count))

    context = {'misconfigurations': list(map(lambda a: a[1], top10_misconfiguration_count)),
               'domains_amount': len(domains),
               'information_id': str(information.id),
               'dns_id': str(dns.id),
               'misconfiguration_data_id': str(misconfiguration_data.id),
               'misconfiguration_count_id': str(misconfiguration_count.id),
               'also_dns': True
               }

    for i, domain in enumerate(domains):
        domain_str_key = 'domain' + str(i)
        context[domain_str_key] = domain

    return context


def handle_misconfiguration(misconfiguration_result):
    misconfiguration_data = StoredDict.objects.create(pickle_dict=pickle.dumps(misconfiguration_result.misconfiguration_dict))
    misconfiguration_count = StoredDict.objects.create(pickle_dict=pickle.dumps(misconfiguration_result.misconfiguration_count_dict))

    sorted_misconfiguration_count = sorted(misconfiguration_result.misconfiguration_count_dict.items(), key=lambda kv: (kv[1], kv[0]), reverse=True)

    top10_misconfiguration_count = sorted_misconfiguration_count[:10]

    domains = list(map(lambda a: a[0], top10_misconfiguration_count))

    context = {'misconfigurations': list(map(lambda a: a[1], top10_misconfiguration_count)),
               'domains_amount': len(domains),
               'information_id': str(-1),
               'dns_id': str(-1),
               'misconfiguration_data_id': str(misconfiguration_data.id),
               'misconfiguration_count_id': str(misconfiguration_count.id)
               }

    for i, domain in enumerate(domains):
        domain_str_key = 'domain' + str(i)
        context[domain_str_key] = domain

    return context


def create_root():
    roots = [["a.root-servers.net", "198.41.0.4", "2001:503:ba3e::2:30", "VeriSign Inc."],
             ["b.root-servers.net", "199.9.14.201", "2001:500:200::b", "University of Southern California (ISI)"],
             ["c.root-servers.net", "192.33.4.12", "2001:500:2::c", "Cogent Communications"],
             ["d.root-servers.net", "199.7.91.13", "2001:500:2d::d", "University of Maryland"],
             ["e.root-servers.net", "192.203.230.10", "2001:500:a8::e", "NASA (Ames Research Center)"],
             ["f.root-servers.net", "192.5.5.241", "2001:500:2f::f", "Internet Systems Consortium Inc."],
             ["g.root-servers.net", "192.112.36.4", "2001:500:12::d0d", "US Department of Defense (NIC)"],
             ["h.root-servers.net", "198.97.190.53", "2001:500:1::53", "US Army (Research Lab)"],
             ["i.root-servers.net", "192.36.148.17", "2001:7fe::53", "Netnod"],
             ["j.root-servers.net", "192.58.128.30", "2001:503:c27::2:30", "VeriSign Inc."],
             ["k.root-servers.net", "193.0.14.129", "2001:7fd::1", "RIPE NCC"],
             ["l.root-servers.net", "199.7.83.42", "2001:500:9f::42", "ICANN"],
             ["m.root-servers.net", "202.12.27.33", "2001:dc3::35", "WIDE Project"]]

    for root in roots:
        if not RootDNSServers.objects.filter(host_name=root[0]).exists():
            RootDNSServers.objects.create(host_name=root[0], ipv4_address=root[1], ipv6_address=root[2], description=root[3])


def index(request):
    # create_root()

    members = list()
    members.append(Member("Tom Nissim", email="tom.nissim1@mail.huji.ac.il", image_alt=""))
    members.append(Member("Tomer Lior", email="tomer.lior@mail.huji.ac.il", image_alt=""))
    members.append(Member("Tom Eliassy", email="tom.eliassy@mail.huji.ac.il", image_alt=""))
    members.append(Member("Haya Shulman", role="Mentor", image_alt=""))

    context = {'team_members': members}
    return render(request, 'DNSmisconfiguration/index.html', context)


def readme(request):
    return render(request, 'DNSmisconfiguration/readme.html')


def address(request):
    if request.method == 'POST':
        form = SingleUrlForm(request.POST)
        if form.is_valid():
            dns_worker, misconfiguration_result = dns_utils.main_url(form.cleaned_data["url"])
            context = handle_dns(dns_worker, misconfiguration_result)
            return render(request, 'DNSmisconfiguration/results.html', context)
    else:
        form = SingleUrlForm()

    return render(request, 'DNSmisconfiguration/address.html', {'form': form})


@csrf_exempt
def csv_url(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            dns_worker, misconfiguration_result = dns_utils.main_csv(request.FILES['file'])
            context = handle_dns(dns_worker, misconfiguration_result)
            context_stored = StoredDict.objects.create(pickle_dict=pickle.dumps(context))
            return HttpResponseRedirect('/results/' + str(context_stored.id))
    else:
        form = UploadFileForm()
    return render(request, 'DNSmisconfiguration/csv.html', {'form': form})


@csrf_exempt
def known_ns(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            utf8 = (line.decode('utf-8') for line in file)
            file_reader = csv.reader(utf8)

            known_ns_dict = dict()
            for counter, row in enumerate(file_reader):
                if row == ['(Server Name, Domain)', 'Servers known in domain']:
                    continue
                elif len(row) == 0:
                    continue
                else:
                    try:
                        tuple_key = literal_eval(row[0])
                        set_value = literal_eval(row[1])
                    except Exception:
                        continue

                    if type(tuple_key) == tuple and type(set_value) == set and len(tuple_key) == 2:
                        known_ns_dict[tuple_key] = set_value
                    else:
                        continue

            misconfiguration_result = dns_utils.main_known_ns(known_ns_dict)
            context = handle_misconfiguration(misconfiguration_result)
            context_stored = StoredDict.objects.create(pickle_dict=pickle.dumps(context))
            return HttpResponseRedirect('/results/' + str(context_stored.id))
    else:
        form = UploadFileForm()
    return render(request, 'DNSmisconfiguration/known_ns.html', {'form': form})


def results(request, dict_id):
    stored_context = get_object_or_404(StoredDict, id=int(dict_id))
    context = pickle.loads(stored_context.pickle_dict)
    return render(request, 'DNSmisconfiguration/results.html', context)


def top500(request):
    file_path = os.path.join(settings.STATIC_ROOT, 'DNSmisconfiguration/500topResults/misconfigurations_count.csv')
    if os.path.exists(file_path):
        misconfigurations_count = dict()
        with open(file_path, 'r') as fh:
            reader = csv.reader(fh)
            for counter, row in enumerate(reader):
                if row == ['domain', 'num of misconfigurations']:
                    continue
                elif len(row) == 0:
                    continue
                else:
                    if int(row[1]) == 0:
                        continue
                    else:
                        misconfigurations_count[row[0]] = int(row[1])

        sorted_misconfiguration_count = sorted(misconfigurations_count.items(), key=lambda kv: (kv[1], kv[0]), reverse=True)

        top10_misconfiguration_count = sorted_misconfiguration_count[:10]

        domains = list(map(lambda a: a[0], top10_misconfiguration_count))

        context = {'misconfigurations': list(map(lambda a: a[1], top10_misconfiguration_count)),
                   'domains_amount': len(domains),
                   'also_dns': True
                   }

        for i, domain in enumerate(domains):
            domain_str_key = 'domain' + str(i)
            context[domain_str_key] = domain

        return render(request, 'DNSmisconfiguration/top500.html', context)
    else:
        raise Http404


class Echo:
    def write(self, value):
        return value


def download_generator(writer, data):
    # yield writer.writeheader()
    for row in data:
        yield writer.writerow(row)


def download_dict(request, dict_id, option):
    int_dict_id = int(dict_id)
    int_option = int(option)

website/dnswebsite/DNSmisconfiguration/templates/DNSmisconfiguration/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>DNS Project</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'DNSmisconfiguration/w3.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
    </style>

    {% block head %}
    {% endblock %}
</head>

<body>

<!-- Navbar -->
{% block navbar %}
<div class="w3-top">
    <div class="w3-bar w3-red w3-card w3-left-align w3-large">
        <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red"
           href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i
                class="fa fa-bars"></i></a>

        {% block navbarHOME %}
        <a href="{% url 'DNSmisconfiguration:index' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Home</a>
        {% endblock %}

        {% block navbarABOUT %}
        <a href="{% url 'DNSmisconfiguration:readme' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">README</a>
        {% endblock %}

        {% block navbarADDRESS %}
        <a href="{% url 'DNSmisconfiguration:address' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Address</a>
        {% endblock %}

        {% block navbarCSV %}
        <a href="{% url 'DNSmisconfiguration:csv_url' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">CSV</a>
        {% endblock %}

        {% block navbarKnownNS %}
        <a href="{% url 'DNSmisconfiguration:known_ns' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">KnownNS</a>
        {% endblock %}

        {% block navbarTop500 %}
        <a href="{% url 'DNSmisconfiguration:top500' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Top500</a>
        {% endblock %}

    </div>

    <!-- Navbar on small screens -->
    <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">

        {% block navbarDemoHOME %}
        <a href="{% url 'DNSmisconfiguration:index' %}" class="w3-bar-item w3-button w3-padding-large">Home</a>
        {% endblock %}

        {% block navbarDemoABOUT %}
        <a href="{% url 'DNSmisconfiguration:readme' %}" class="w3-bar-item w3-button w3-padding-large">README</a>
        {% endblock %}

        {% block navbarDemoADDRESS %}
        <a href="{% url 'DNSmisconfiguration:address' %}" class="w3-bar-item w3-button w3-padding-large">Address</a>
        {% endblock %}

        {% block navbarDemoCSV %}
        <a href="{% url 'DNSmisconfiguration:csv_url' %}" class="w3-bar-item w3-button w3-padding-large">CSV</a>
        {% endblock %}

        {% block navbarDemoKnownNS %}
        <a href="{% url 'DNSmisconfiguration:known_ns' %}" class="w3-bar-item w3-button w3-padding-large">KnownNS</a>
        {% endblock %}

        {% block navbarDemoTop500 %}
        <a href="{% url 'DNSmisconfiguration:top500' %}" class="w3-bar-item w3-button w3-padding-large">Top500</a>
        {% endblock %}

    </div>
</div>
{% endblock %}


{% block distance %}
<div style="padding:50px 0px 0px 0px">
</div>
{% endblock %}


<!--Content-->
{% block content %}
{% endblock %}


<!-- Header -->
{% block header %}
{% endblock %}


{% block grid %}

<!-- First Grid -->
{% block firstgrid %}
{% endblock %}


<!-- Second Grid -->
{% block secondgrid %}
{% endblock %}

{% endblock %}


<!-- Team Section -->
{% block team %}
{% endblock %}


<!-- Gray Bar -->
{% block graybar %}
<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">DNS Misconfiguration Project: 67914 Communication Networks Security: HUJI 2017/18</h1>
</div>
{% endblock %}


<!-- Footer -->
{% block footer %}
<!--<footer class="w3-container w3-padding-64 w3-center w3-opacity">-->
    <!--<div class="w3-xlarge w3-padding-32">-->
        <!--<i class="fa fa-facebook-official w3-hover-opacity"></i>-->
        <!--<i class="fa fa-instagram w3-hover-opacity"></i>-->
        <!--<i class="fa fa-snapchat w3-hover-opacity"></i>-->
        <!--<i class="fa fa-pinterest-p w3-hover-opacity"></i>-->
        <!--<i class="fa fa-twitter w3-hover-opacity"></i>-->
        <!--<i class="fa fa-linkedin w3-hover-opacity"></i>-->
    <!--</div>-->
<!--</footer>-->
{% endblock %}


<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

website/dnswebsite/DNSmisconfiguration/templates/DNSmisconfiguration/readme.html
{% extends "DNSmisconfiguration/base.html" %}


{% block head %}

<style>
    p {color:#757575!important}
</style>
{% endblock %}


{% block navbarABOUT %}
<a href="{% url 'DNSmisconfiguration:readme' %}" class="w3-bar-item w3-button w3-padding-large w3-white">README</a>
{% endblock %}

{% block navbarDemoABOUT %}
<a href="{% url 'DNSmisconfiguration:readme' %}" class="w3-bar-item w3-button w3-padding-large w3-gray">README</a>
{% endblock %}


{% block content %}

<header class="w3-container w3-red w3-center" style="padding:128px 16px">
    <h1 class="w3-margin">DNS Misconfiguration Project</h1>
    <h3 class="w3-margin">DNS Misconfiguration Detection Tool</h3>
    <h3 class="w3-margin">67914 Communication Networks Security: HUJI 2017/18</h3>
</header>

<!--<div class="w3-row-padding w3-padding-64 w3-container">-->
    <!--<div class="w3-content">-->
        <!--<h1 id="dns-misconfiguration-detection-tool">DNS misconfiguration detection tool</h1>-->
        <!--<h2 id="networks-security-course-67914">67914 Communication Networks Security: HUJI 2017/18</h2>-->
    <!--</div>-->
<!--</div>-->

<div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-content">
        <h1 id="abstract">Abstract</h1>
        <!--<h5 class="w3-padding-32">see <a href="https://ns1.com/resources/dns-protocol">DNS protocol</a></h5>-->

        <p>Tool for detecting and analyzing DNS misconfigurations among the internet servers.The tool scans through a list of URL addresses, and checks whether their authoritative servers are misconfigured.</p>
        <p>The program is executed through a website that hosted in AWS.</p>
    </div>
</div>

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <h1 id="usage">Usage</h1>
        <h3 class="w3-padding-32" id="the-program-supports-2-execution-modes">The program supports 3 execution modes:</h3>
        <h4 id="single-url">1. Single URL</h4>
        <blockquote>
        <p>receives a single url address via designated text box in the website UI.</p>
        </blockquote>
        <blockquote>
        <p>for example: walla.co.il</p>
        </blockquote>
        <h4 id="multiple-urls-in-csv-format">2. Multiple URLs in CSV format</h4>
        <blockquote>
        <p>receives a csv uploaded to the designated upload box. The csv file consists of the URLs that will be checked, in the following format:</p>
        </blockquote>
        <blockquote>
        <p>URL_1</p>
        </blockquote>
        <blockquote>
        <p>URL_2</p>
        </blockquote>
        <blockquote>
        <p>...</p>
        </blockquote>
        <blockquote>
        <p>URL_N</p>
        </blockquote>
        <blockquote>
        <p>for example: input.csv:</p>
        </blockquote>
        <blockquote>
        <p>google.com</p>
        </blockquote>
        <blockquote>
        <p>walla.co.il</p>
        </blockquote>
        <blockquote>
        <p>packetlife.net</p>
        </blockquote>
        <blockquote>
        <p>moodle2.cs.huji.ac.il</p>
        </blockquote>
        <h4>3. CSV File of type "results_records"</h4>
        <blockquote>
        <p>This file is produced by using one of the above usages to run program.</p>
        </blockquote>
        <blockquote>
        <p>Explanation about the file of type "results_records.csv" is below.</p>
        </blockquote>
    </div>
</div>


<div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-content">
        <h1 id="process-and-output">Process and Output</h1>
        <h3 id="the-program-performs-two-stages">The program performs two stages</h3>
        <h4 class="w3-padding-32" id="information-gathering-and-data-base-construction">Information gathering and Data Base construction</h4>
        <blockquote>
        <p>the program breaks each URL in to sub-domains, for each sub domain the program collects DNS data.</p>
        </blockquote>
        <blockquote>
        <p>The program will output <strong>two</strong> csv files consists of the data it collected:</p>
        </blockquote>
        <blockquote>
        <ol style="list-style-type: decimal">
        <li><strong>results_servers.csv</strong></li>
        </ol>
        </blockquote>
        <blockquote>
        <p>a csv file consists of the data collected on each server that participated in the dns process for the sub-domain.</p>
        </blockquote>
        <blockquote>
        <p>The file is in the format of:</p>
        </blockquote>
        <blockquote>
        <p>(server name) , (server information)</p>
        </blockquote>
        <blockquote>
        <p>server information holds the following attributes for a specific server:</p>
        </blockquote>
        <blockquote>
        <ul>
        <li>host name</li>
        <li>domain</li>
        <li>ipv4 addresses</li>
        <li>ipv6 addresses</li>
        <li>description</li>
        </ul>
        </blockquote>
        <blockquote>
        <p>for additional information related to format download <a href="{% url 'DNSmisconfiguration:download_results_servers' %}"> results_servers.csv </a> example</p>
        </blockquote>
        <blockquote>
        <ol start="2" style="list-style-type: decimal">
        <li><strong>results_records.csv</strong></li>
        </ol>
        </blockquote>
        <blockquote>
        <p>a csv file in which each record consists of a <em>name server</em>, a domain and the name servers that the <em>name server</em> knows in the domain</p>
        </blockquote>
        <blockquote>
        <p>The file is in the format of:</p>
        </blockquote>
        <blockquote>
        <p>(server name, domain) , (servers known in the domain)</p>
        </blockquote>
        <blockquote>
        <p>for additional information related to format download <a href="{% url 'DNSmisconfiguration:download_results_records' %}"> results_records.csv </a> example</p>
        </blockquote>
        <h4 id="misconfigurations-detection">Misconfigurations Detection</h4>
        <blockquote>
        <p>the program uses the data it collected in the previous stage and analyzes it in order to discover misconfigurations.</p>
        </blockquote>
        <blockquote>
        <p>A misconfiguration is defined to be a state in which two servers &quot;knows&quot; different servers in the same domain, one server knows more name servers (or less) in the same domain.</p>
        </blockquote>
        <blockquote>
        <p>The program will output <strong>two</strong> csv files consists of the misconfiguration it detected:</p>
        </blockquote>
        <blockquote>
        <ol style="list-style-type: decimal">
        <li><strong>misconfigurations.csv</strong></li>
        </ol>
        </blockquote>
        <blockquote>
        <p>a csv file consists of the misconfigurations that were discovered.</p>
        </blockquote>
        <blockquote>
        <p>The file is in the format of:</p>
        </blockquote>
        <blockquote>
        <p>(server1, server2, domain) , (Misconfiguration information)</p>
        </blockquote>
        <blockquote>
        <p>Misconfiguration information holds the following attributes for a specific misconfiguration:</p>
        </blockquote>
        <blockquote>
        <ul>
        <li>host name</li>
        <li>domain</li>
        <li>first server</li>
        <li>second server</li>
        <li>the servers that both servers know</li>
        </ul>
        </blockquote>
        <blockquote>
        <ul>
        <li>the servers that the <em>first server</em> knows and the <em>second server</em> does not</li>
        <li>the servers that the <em>second server</em> knows and the <em>first server</em> does not</li>
        </ul>
        </blockquote>
        <blockquote>
        <p>for additional information related to format download <a href="{% url 'DNSmisconfiguration:download_misconfigurations' %}"> misconfigurations.csv </a> example</p>
        </blockquote>
        <blockquote>
        <ol start="2" style="list-style-type: decimal">
        <li><strong>misconfigurations_count.csv</strong></li>
        </ol>
        </blockquote>
        <blockquote>
        <p>a csv file in which each record consists of a <em>domain</em>, and the number of misconfigurations detected for the <em>domain</em></p>
        </blockquote>
        <blockquote>
        <p>The file is in the format of:</p>
        </blockquote>
        <blockquote>
        <p>(domain) , (number of misconfigurations detected)</p>
        </blockquote>
        <blockquote>
        <p>for additional information related to format download <a href="{% url 'DNSmisconfiguration:download_misconfigurations_count' %}"> misconfigurations_count.csv </a> example</p>
        </blockquote>
        <p><strong>In addition to the downloadable csv files, the results are stored in a Django database contained in the website </strong></p>
    </div>
</div>


{% endblock %}